// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/bug/ent/datafield"
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DataFieldDelete is the builder for deleting a DataField entity.
type DataFieldDelete struct {
	config
	hooks    []Hook
	mutation *DataFieldMutation
}

// Where appends a list predicates to the DataFieldDelete builder.
func (dfd *DataFieldDelete) Where(ps ...predicate.DataField) *DataFieldDelete {
	dfd.mutation.Where(ps...)
	return dfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dfd *DataFieldDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dfd.hooks) == 0 {
		affected, err = dfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DataFieldMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dfd.mutation = mutation
			affected, err = dfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dfd.hooks) - 1; i >= 0; i-- {
			if dfd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dfd *DataFieldDelete) ExecX(ctx context.Context) int {
	n, err := dfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dfd *DataFieldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: datafield.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: datafield.FieldID,
			},
		},
	}
	if ps := dfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// DataFieldDeleteOne is the builder for deleting a single DataField entity.
type DataFieldDeleteOne struct {
	dfd *DataFieldDelete
}

// Exec executes the deletion query.
func (dfdo *DataFieldDeleteOne) Exec(ctx context.Context) error {
	n, err := dfdo.dfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{datafield.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dfdo *DataFieldDeleteOne) ExecX(ctx context.Context) {
	dfdo.dfd.ExecX(ctx)
}
