// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entgo.io/bug/ent/datafield"
	"entgo.io/bug/ent/record"
	"entgo.io/bug/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	datafieldFields := schema.DataField{}.Fields()
	_ = datafieldFields
	// datafieldDescID is the schema descriptor for id field.
	datafieldDescID := datafieldFields[0].Descriptor()
	// datafield.DefaultID holds the default value on creation for the id field.
	datafield.DefaultID = datafieldDescID.Default.(func() uuid.UUID)
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescID is the schema descriptor for id field.
	recordDescID := recordFields[0].Descriptor()
	// record.DefaultID holds the default value on creation for the id field.
	record.DefaultID = recordDescID.Default.(func() uuid.UUID)
}
