// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cell is the predicate function for cell builders.
type Cell func(*sql.Selector)

// DataField is the predicate function for datafield builders.
type DataField func(*sql.Selector)

// Record is the predicate function for record builders.
type Record func(*sql.Selector)
